{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "File Metadata List:\n",
      "Filename: .gitattributes, SHA: 11ad7efa24975ee4b0c3c3a38ed18737f0658a5f75a0a96787b576a78a023361, Size: 1519\n",
      "Filename: LICENSE, SHA: 41c2cf8c272f6fb0080a97cd9d9bd7d4604072b80a0b10e7d65ca26ef5000c0c, Size: 7281\n",
      "Filename: README.md, SHA: a1f74fb8b65e90381e38aecb1f97f035d58b886a8ba327373ee203cd15074703, Size: 2773\n",
      "Filename: config.json, SHA: fa5ce2577a12b2c41aab208242c3de5bdcc4309d147842ad88040b6d4349fc36, Size: 661\n",
      "Filename: generation_config.json, SHA: 8c970692323e3ea0e9b8b0a4dca79388d31226e41f83c9fd6014804280ebf6e8, Size: 138\n",
      "Filename: merges.txt, SHA: 599bab54075088774b1733fde865d5bd747cbcc7a547c5bc12610e874e26f5e3, Size: 1671839\n",
      "Filename: model.safetensors, SHA: a88bcf41b3fa9a20031b6b598abc11f694e35e0b5684d6e14dbe7e894ebbb080, Size: 1239173352\n",
      "Filename: tokenizer.json, SHA: f7c9b2dba4a296b1aa76c16a34b8225c0c118978400d4bb66bff0902d702f5b8, Size: 7028015\n",
      "Filename: tokenizer_config.json, SHA: 80d64fccf954f022eb43b7425eb45a133cbb92c76a5f24d4cea6dbe3d45548d9, Size: 1289\n",
      "Filename: vocab.json, SHA: ca10d7e9fb3ed18575dd1e277a2579c16d108e32f27439684afa0e10b1440910, Size: 2776833\n"
     ]
    },
    {
     "ename": "OSError",
     "evalue": "/home/ks/repos/april-oss/flow-merge/notebooks/Qwen/Qwen1.5-0.5B does not appear to have a file named config.json. Checkout 'https://huggingface.co//home/ks/repos/april-oss/flow-merge/notebooks/Qwen/Qwen1.5-0.5B/None' for available files.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOSError\u001b[0m                                   Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[38], line 30\u001b[0m\n\u001b[1;32m     27\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mFilename: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfile_metadata\u001b[38;5;241m.\u001b[39mfilename\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m, SHA: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfile_metadata\u001b[38;5;241m.\u001b[39msha\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m, Size: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfile_metadata\u001b[38;5;241m.\u001b[39msize\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m     29\u001b[0m \u001b[38;5;66;03m# Load the model using the Model class and the path or Hugging Face model ID\u001b[39;00m\n\u001b[0;32m---> 30\u001b[0m model \u001b[38;5;241m=\u001b[39m \u001b[43mModel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfrom_path\u001b[49m\u001b[43m(\u001b[49m\u001b[43mPath\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpath_or_id\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdirectory_settings\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mDirectorySettings\u001b[49m\u001b[43m(\u001b[49m\u001b[43mlocal_dir\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43m.\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     32\u001b[0m \u001b[38;5;66;03m# Display the model attributes to verify correct instantiation\u001b[39;00m\n\u001b[1;32m     33\u001b[0m \u001b[38;5;66;03m# print(\"\\nModel Attributes:\")\u001b[39;00m\n\u001b[1;32m     34\u001b[0m \u001b[38;5;66;03m# print(f\"ID: {model.id}\")\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     40\u001b[0m \u001b[38;5;66;03m# print(f\"Revision: {model.revision}\")\u001b[39;00m\n\u001b[1;32m     41\u001b[0m \u001b[38;5;66;03m# print(f\"Trust Remote Code: {model.trust_remote_code}\")\u001b[39;00m\n",
      "File \u001b[0;32m~/repos/april-oss/flow-merge/flow_merge/lib/model.py:33\u001b[0m, in \u001b[0;36mModel.from_path\u001b[0;34m(cls, path, directory_settings)\u001b[0m\n\u001b[1;32m     31\u001b[0m file_to_tensor_index \u001b[38;5;241m=\u001b[39m TensorIndexService\u001b[38;5;241m.\u001b[39mcreate_file_to_tensor_index(metadata)\n\u001b[1;32m     32\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m metadata\u001b[38;5;241m.\u001b[39mhf_exists \u001b[38;5;129;01mand\u001b[39;00m metadata\u001b[38;5;241m.\u001b[39mhas_config:\n\u001b[0;32m---> 33\u001b[0m     config \u001b[38;5;241m=\u001b[39m \u001b[43mAutoConfig\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfrom_pretrained\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mmetadata\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mabsolute_path\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     34\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     35\u001b[0m     config \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1111\u001b[0m, in \u001b[0;36mAutoConfig.from_pretrained\u001b[0;34m(cls, pretrained_model_name_or_path, **kwargs)\u001b[0m\n\u001b[1;32m   1108\u001b[0m trust_remote_code \u001b[38;5;241m=\u001b[39m kwargs\u001b[38;5;241m.\u001b[39mpop(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtrust_remote_code\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[1;32m   1109\u001b[0m code_revision \u001b[38;5;241m=\u001b[39m kwargs\u001b[38;5;241m.\u001b[39mpop(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcode_revision\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[0;32m-> 1111\u001b[0m config_dict, unused_kwargs \u001b[38;5;241m=\u001b[39m \u001b[43mPretrainedConfig\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_config_dict\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpretrained_model_name_or_path\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1112\u001b[0m has_remote_code \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mauto_map\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m config_dict \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mAutoConfig\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m config_dict[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mauto_map\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n\u001b[1;32m   1113\u001b[0m has_local_code \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmodel_type\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m config_dict \u001b[38;5;129;01mand\u001b[39;00m config_dict[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmodel_type\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;129;01min\u001b[39;00m CONFIG_MAPPING\n",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/transformers/configuration_utils.py:633\u001b[0m, in \u001b[0;36mPretrainedConfig.get_config_dict\u001b[0;34m(cls, pretrained_model_name_or_path, **kwargs)\u001b[0m\n\u001b[1;32m    631\u001b[0m original_kwargs \u001b[38;5;241m=\u001b[39m copy\u001b[38;5;241m.\u001b[39mdeepcopy(kwargs)\n\u001b[1;32m    632\u001b[0m \u001b[38;5;66;03m# Get config dict associated with the base config file\u001b[39;00m\n\u001b[0;32m--> 633\u001b[0m config_dict, kwargs \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mcls\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_get_config_dict\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpretrained_model_name_or_path\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    634\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_commit_hash\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m config_dict:\n\u001b[1;32m    635\u001b[0m     original_kwargs[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_commit_hash\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m config_dict[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_commit_hash\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/transformers/configuration_utils.py:688\u001b[0m, in \u001b[0;36mPretrainedConfig._get_config_dict\u001b[0;34m(cls, pretrained_model_name_or_path, **kwargs)\u001b[0m\n\u001b[1;32m    684\u001b[0m configuration_file \u001b[38;5;241m=\u001b[39m kwargs\u001b[38;5;241m.\u001b[39mpop(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_configuration_file\u001b[39m\u001b[38;5;124m\"\u001b[39m, CONFIG_NAME)\n\u001b[1;32m    686\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    687\u001b[0m     \u001b[38;5;66;03m# Load from local folder or from cache or download from model Hub and cache\u001b[39;00m\n\u001b[0;32m--> 688\u001b[0m     resolved_config_file \u001b[38;5;241m=\u001b[39m \u001b[43mcached_file\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    689\u001b[0m \u001b[43m        \u001b[49m\u001b[43mpretrained_model_name_or_path\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    690\u001b[0m \u001b[43m        \u001b[49m\u001b[43mconfiguration_file\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    691\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcache_dir\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcache_dir\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    692\u001b[0m \u001b[43m        \u001b[49m\u001b[43mforce_download\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mforce_download\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    693\u001b[0m \u001b[43m        \u001b[49m\u001b[43mproxies\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mproxies\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    694\u001b[0m \u001b[43m        \u001b[49m\u001b[43mresume_download\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mresume_download\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    695\u001b[0m \u001b[43m        \u001b[49m\u001b[43mlocal_files_only\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mlocal_files_only\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    696\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtoken\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtoken\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    697\u001b[0m \u001b[43m        \u001b[49m\u001b[43muser_agent\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43muser_agent\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    698\u001b[0m \u001b[43m        \u001b[49m\u001b[43mrevision\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrevision\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    699\u001b[0m \u001b[43m        \u001b[49m\u001b[43msubfolder\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msubfolder\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    700\u001b[0m \u001b[43m        \u001b[49m\u001b[43m_commit_hash\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcommit_hash\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    701\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    702\u001b[0m     commit_hash \u001b[38;5;241m=\u001b[39m extract_commit_hash(resolved_config_file, commit_hash)\n\u001b[1;32m    703\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mEnvironmentError\u001b[39;00m:\n\u001b[1;32m    704\u001b[0m     \u001b[38;5;66;03m# Raise any environment error raise by `cached_file`. It will have a helpful error message adapted to\u001b[39;00m\n\u001b[1;32m    705\u001b[0m     \u001b[38;5;66;03m# the original exception.\u001b[39;00m\n",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/transformers/utils/hub.py:369\u001b[0m, in \u001b[0;36mcached_file\u001b[0;34m(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_gated_repo, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)\u001b[0m\n\u001b[1;32m    367\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m os\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39misfile(resolved_file):\n\u001b[1;32m    368\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m _raise_exceptions_for_missing_entries:\n\u001b[0;32m--> 369\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mEnvironmentError\u001b[39;00m(\n\u001b[1;32m    370\u001b[0m             \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mpath_or_repo_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m does not appear to have a file named \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfull_filename\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m. Checkout \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    371\u001b[0m             \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mhttps://huggingface.co/\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mpath_or_repo_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m/\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mrevision\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m for available files.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    372\u001b[0m         )\n\u001b[1;32m    373\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    374\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "\u001b[0;31mOSError\u001b[0m: /home/ks/repos/april-oss/flow-merge/notebooks/Qwen/Qwen1.5-0.5B does not appear to have a file named config.json. Checkout 'https://huggingface.co//home/ks/repos/april-oss/flow-merge/notebooks/Qwen/Qwen1.5-0.5B/None' for available files."
     ]
    }
   ],
   "source": [
    "try:\n",
    "    %load_ext autoreload --quiet\n",
    "except ImportError:\n",
    "    %reload_ext autoreload \n",
    "%autoreload 2\n",
    "\n",
    "# Import necessary modules\n",
    "from pathlib import Path\n",
    "from flow_merge.lib.merge_settings import DirectorySettings\n",
    "from flow_merge.lib.model import Model\n",
    "from flow_merge.lib.model_metadata import ModelMetadataService\n",
    "#from flow_merge.lib.model_metadata import ModelMetadataService\n",
    "\n",
    "# Define the chunk size for hashing large files (used in model_metadata.py)\n",
    "CHUNK_SIZE = 64 * 1024  # 64KB\n",
    "\n",
    "# Specify the path or Hugging Face model ID to test\n",
    "path_or_id = \"Qwen/Qwen1.5-0.5B\"\n",
    "\n",
    "# Load the model metadata from the specified path or Hugging Face model ID\n",
    "metadata_service = ModelMetadataService()\n",
    "model_metadata = metadata_service.load_model_info(path_or_id)\n",
    "\n",
    "# Display the file metadata list to verify correct loading\n",
    "print(\"File Metadata List:\")\n",
    "for file_metadata in model_metadata.file_metadata_list:\n",
    "    print(f\"Filename: {file_metadata.filename}, SHA: {file_metadata.sha}, Size: {file_metadata.size}\")\n",
    "\n",
    "print(model_metadata.config)\n",
    "print(model_metadata.has_config)\n",
    "\n",
    "# Load the model using the Model class and the path or Hugging Face model ID\n",
    "model = Model.from_path(Path(path_or_id), directory_settings=DirectorySettings(local_dir=\".\"))\n",
    "\n",
    "# Display the model attributes to verify correct instantiation\n",
    "# print(\"\\nModel Attributes:\")\n",
    "# print(f\"ID: {model.id}\")\n",
    "# print(f\"Path: {model.path}\")\n",
    "# print(f\"Metadata: {model.metadata}\")\n",
    "# print(f\"File to Tensor Index: {model.file_to_tensor_index}\")\n",
    "# print(f\"Shards: {model.shards}\")\n",
    "# print(f\"Config: {model.config}\")\n",
    "# print(f\"Revision: {model.revision}\")\n",
    "# print(f\"Trust Remote Code: {model.trust_remote_code}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n",
      "[autoreload of flow_merge.lib.tensor_loader failed: Traceback (most recent call last):\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/ks/.conda/envs/flow-merge/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/ks/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py\", line 13, in <module>\n",
      "    from huggingface_hub import hf_hub_download, RepositoryNotFoundError, RevisionNotFoundError, EntryNotFoundError, LocalEntryNotFoundError\n",
      "ImportError: cannot import name 'RepositoryNotFoundError' from 'huggingface_hub' (/home/ks/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/__init__.py)\n",
      "]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Safetensors index not found: 404 Client Error. (Request ID: Root=1-664cbbcc-1e775f5b7b3d06ee10202c26;1259d51c-c7ef-4f6a-8a13-92c9afc8ecea)\n",
      "\n",
      "Entry Not Found for url: https://huggingface.co/Qwen/Qwen1.5-0.5B/resolve/main/model.safetensors.index.json.\n",
      "Pytorch bin index not found: 404 Client Error. (Request ID: Root=1-664cbbcc-11a08bee48d4585a0fb5fa7c;3be97f8e-76e6-4574-9b96-64d236fe8a2d)\n",
      "\n",
      "Entry Not Found for url: https://huggingface.co/Qwen/Qwen1.5-0.5B/resolve/main/pytorch_model.bin.index.json.\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "Failed to download model.safetensors from Qwen/Qwen1.5-0.5B: 416 Client Error: Requested Range Not Satisfiable for url: https://cdn-lfs-us-1.huggingface.co/repos/68/82/6882b504b120594058440b1fa4f2dba656dac125cc5e12dc9637f72229c9ea71/a88bcf41b3fa9a20031b6b598abc11f694e35e0b5684d6e14dbe7e894ebbb080?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1716562260&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxNjU2MjI2MH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzY4LzgyLzY4ODJiNTA0YjEyMDU5NDA1ODQ0MGIxZmE0ZjJkYmE2NTZkYWMxMjVjYzVlMTJkYzk2MzdmNzIyMjljOWVhNzEvYTg4YmNmNDFiM2ZhOWEyMDAzMWI2YjU5OGFiYzExZjY5NGUzNWUwYjU2ODRkNmUxNGRiZTdlODk0ZWJiYjA4MD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=NwBGl4p6PA7wYwoLJlt5ifg518J9G4-HfVWVOIOqW9jDhwlFo42MeckN7y0Nh1ShS~r4XsTOhqBEK1948wTJTKbnrAaxzZCEW3~aorw-oQI6xaJLlj-7N4SpLexpe6WZt6gt2F2ukCpomu8gq83k0BUkYvol9~VQ4FPmtfm608EPkOQW~YWtkwhR8NjKh9Rdj2sY5AIx4fMmbkx6dQVHcvLOPucdKak9d6RQIv5pz7oww1rVipl40ZPjH2ILwBMEjwz59kd9DidKEer2KBwlnDPfojqetBUaYiZ4d9rlQXYbR~n9fyn9CA3XSMuSZzrO8XgeN5rqQDhNlE7bmTV2GA__&Key-Pair-Id=KCD77M1F0VK2B",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mHTTPError\u001b[0m                                 Traceback (most recent call last)",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py:304\u001b[0m, in \u001b[0;36mhf_raise_for_status\u001b[0;34m(response, endpoint_name)\u001b[0m\n\u001b[1;32m    303\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 304\u001b[0m     \u001b[43mresponse\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mraise_for_status\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    305\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m HTTPError \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/requests/models.py:1021\u001b[0m, in \u001b[0;36mResponse.raise_for_status\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1020\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m http_error_msg:\n\u001b[0;32m-> 1021\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m HTTPError(http_error_msg, response\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m)\n",
      "\u001b[0;31mHTTPError\u001b[0m: 416 Client Error: Requested Range Not Satisfiable for url: https://cdn-lfs-us-1.huggingface.co/repos/68/82/6882b504b120594058440b1fa4f2dba656dac125cc5e12dc9637f72229c9ea71/a88bcf41b3fa9a20031b6b598abc11f694e35e0b5684d6e14dbe7e894ebbb080?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1716562260&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxNjU2MjI2MH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzY4LzgyLzY4ODJiNTA0YjEyMDU5NDA1ODQ0MGIxZmE0ZjJkYmE2NTZkYWMxMjVjYzVlMTJkYzk2MzdmNzIyMjljOWVhNzEvYTg4YmNmNDFiM2ZhOWEyMDAzMWI2YjU5OGFiYzExZjY5NGUzNWUwYjU2ODRkNmUxNGRiZTdlODk0ZWJiYjA4MD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=NwBGl4p6PA7wYwoLJlt5ifg518J9G4-HfVWVOIOqW9jDhwlFo42MeckN7y0Nh1ShS~r4XsTOhqBEK1948wTJTKbnrAaxzZCEW3~aorw-oQI6xaJLlj-7N4SpLexpe6WZt6gt2F2ukCpomu8gq83k0BUkYvol9~VQ4FPmtfm608EPkOQW~YWtkwhR8NjKh9Rdj2sY5AIx4fMmbkx6dQVHcvLOPucdKak9d6RQIv5pz7oww1rVipl40ZPjH2ILwBMEjwz59kd9DidKEer2KBwlnDPfojqetBUaYiZ4d9rlQXYbR~n9fyn9CA3XSMuSZzrO8XgeN5rqQDhNlE7bmTV2GA__&Key-Pair-Id=KCD77M1F0VK2B",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mHfHubHTTPError\u001b[0m                            Traceback (most recent call last)",
      "File \u001b[0;32m~/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py:51\u001b[0m, in \u001b[0;36mdownload_file\u001b[0;34m(repo_id, filename, local_dir)\u001b[0m\n\u001b[1;32m     50\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m---> 51\u001b[0m     file_path \u001b[38;5;241m=\u001b[39m \u001b[43mhf_hub_download\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m     52\u001b[0m \u001b[43m        \u001b[49m\u001b[43mrepo_id\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     53\u001b[0m \u001b[43m        \u001b[49m\u001b[43mlocal_dir\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mlocal_dir\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# Convert Path to str for hf_hub_download\u001b[39;49;00m\n\u001b[1;32m     54\u001b[0m \u001b[43m        \u001b[49m\u001b[43mresume_download\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m     55\u001b[0m \u001b[43m        \u001b[49m\u001b[43mforce_download\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m     56\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtoken\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mconfig\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mhf_token\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     57\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     58\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m Path(file_path)  \u001b[38;5;66;03m# Convert returned file_path to Path\u001b[39;00m\n",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py:118\u001b[0m, in \u001b[0;36mvalidate_hf_hub_args.<locals>._inner_fn\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    116\u001b[0m     kwargs \u001b[38;5;241m=\u001b[39m smoothly_deprecate_use_auth_token(fn_name\u001b[38;5;241m=\u001b[39mfn\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m, has_token\u001b[38;5;241m=\u001b[39mhas_token, kwargs\u001b[38;5;241m=\u001b[39mkwargs)\n\u001b[0;32m--> 118\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/file_download.py:1492\u001b[0m, in \u001b[0;36mhf_hub_download\u001b[0;34m(repo_id, filename, subfolder, repo_type, revision, library_name, library_version, cache_dir, local_dir, local_dir_use_symlinks, user_agent, force_download, force_filename, proxies, etag_timeout, resume_download, token, local_files_only, legacy_cache_layout, endpoint)\u001b[0m\n\u001b[1;32m   1490\u001b[0m             _check_disk_space(expected_size, local_dir)\n\u001b[0;32m-> 1492\u001b[0m     \u001b[43mhttp_get\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1493\u001b[0m \u001b[43m        \u001b[49m\u001b[43murl_to_download\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1494\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtemp_file\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1495\u001b[0m \u001b[43m        \u001b[49m\u001b[43mproxies\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mproxies\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1496\u001b[0m \u001b[43m        \u001b[49m\u001b[43mresume_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mresume_size\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1497\u001b[0m \u001b[43m        \u001b[49m\u001b[43mheaders\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1498\u001b[0m \u001b[43m        \u001b[49m\u001b[43mexpected_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mexpected_size\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1499\u001b[0m \u001b[43m        \u001b[49m\u001b[43mdisplayed_filename\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1500\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1502\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m local_dir \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/file_download.py:471\u001b[0m, in \u001b[0;36mhttp_get\u001b[0;34m(url, temp_file, proxies, resume_size, headers, expected_size, displayed_filename, _nb_retries)\u001b[0m\n\u001b[1;32m    469\u001b[0m     headers[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mRange\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mbytes=\u001b[39m\u001b[38;5;132;01m%d\u001b[39;00m\u001b[38;5;124m-\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m%\u001b[39m (resume_size,)\n\u001b[0;32m--> 471\u001b[0m r \u001b[38;5;241m=\u001b[39m \u001b[43m_request_wrapper\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    472\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmethod\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mGET\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstream\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mproxies\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mproxies\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mheaders\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mHF_HUB_DOWNLOAD_TIMEOUT\u001b[49m\n\u001b[1;32m    473\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    474\u001b[0m hf_raise_for_status(r)\n",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/file_download.py:409\u001b[0m, in \u001b[0;36m_request_wrapper\u001b[0;34m(method, url, follow_relative_redirects, **params)\u001b[0m\n\u001b[1;32m    408\u001b[0m response \u001b[38;5;241m=\u001b[39m get_session()\u001b[38;5;241m.\u001b[39mrequest(method\u001b[38;5;241m=\u001b[39mmethod, url\u001b[38;5;241m=\u001b[39murl, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mparams)\n\u001b[0;32m--> 409\u001b[0m \u001b[43mhf_raise_for_status\u001b[49m\u001b[43m(\u001b[49m\u001b[43mresponse\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    410\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m response\n",
      "File \u001b[0;32m~/.conda/envs/flow-merge/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py:362\u001b[0m, in \u001b[0;36mhf_raise_for_status\u001b[0;34m(response, endpoint_name)\u001b[0m\n\u001b[1;32m    360\u001b[0m \u001b[38;5;66;03m# Convert `HTTPError` into a `HfHubHTTPError` to display request information\u001b[39;00m\n\u001b[1;32m    361\u001b[0m \u001b[38;5;66;03m# as well (request id and/or server error message)\u001b[39;00m\n\u001b[0;32m--> 362\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m HfHubHTTPError(\u001b[38;5;28mstr\u001b[39m(e), response\u001b[38;5;241m=\u001b[39mresponse) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01me\u001b[39;00m\n",
      "\u001b[0;31mHfHubHTTPError\u001b[0m: 416 Client Error: Requested Range Not Satisfiable for url: https://cdn-lfs-us-1.huggingface.co/repos/68/82/6882b504b120594058440b1fa4f2dba656dac125cc5e12dc9637f72229c9ea71/a88bcf41b3fa9a20031b6b598abc11f694e35e0b5684d6e14dbe7e894ebbb080?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1716562260&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxNjU2MjI2MH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzY4LzgyLzY4ODJiNTA0YjEyMDU5NDA1ODQ0MGIxZmE0ZjJkYmE2NTZkYWMxMjVjYzVlMTJkYzk2MzdmNzIyMjljOWVhNzEvYTg4YmNmNDFiM2ZhOWEyMDAzMWI2YjU5OGFiYzExZjY5NGUzNWUwYjU2ODRkNmUxNGRiZTdlODk0ZWJiYjA4MD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=NwBGl4p6PA7wYwoLJlt5ifg518J9G4-HfVWVOIOqW9jDhwlFo42MeckN7y0Nh1ShS~r4XsTOhqBEK1948wTJTKbnrAaxzZCEW3~aorw-oQI6xaJLlj-7N4SpLexpe6WZt6gt2F2ukCpomu8gq83k0BUkYvol9~VQ4FPmtfm608EPkOQW~YWtkwhR8NjKh9Rdj2sY5AIx4fMmbkx6dQVHcvLOPucdKak9d6RQIv5pz7oww1rVipl40ZPjH2ILwBMEjwz59kd9DidKEer2KBwlnDPfojqetBUaYiZ4d9rlQXYbR~n9fyn9CA3XSMuSZzrO8XgeN5rqQDhNlE7bmTV2GA__&Key-Pair-Id=KCD77M1F0VK2B",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[23], line 4\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpathlib\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Path\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mflow_merge\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mlib\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmodel\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Model\n\u001b[0;32m----> 4\u001b[0m mo \u001b[38;5;241m=\u001b[39m \u001b[43mModel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfrom_path\u001b[49m\u001b[43m(\u001b[49m\u001b[43mPath\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpath_or_id\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/repos/april-oss/flow-merge/flow_merge/lib/model.py:36\u001b[0m, in \u001b[0;36mModel.from_path\u001b[0;34m(cls, path, directory_settings)\u001b[0m\n\u001b[1;32m     34\u001b[0m     relevant_files \u001b[38;5;241m=\u001b[39m [file \u001b[38;5;28;01mfor\u001b[39;00m file \u001b[38;5;129;01min\u001b[39;00m metadata\u001b[38;5;241m.\u001b[39mfile_metadata_list \u001b[38;5;28;01mif\u001b[39;00m is_model_file(file\u001b[38;5;241m.\u001b[39mfilename)]\n\u001b[1;32m     35\u001b[0m     single_file \u001b[38;5;241m=\u001b[39m relevant_files[\u001b[38;5;241m0\u001b[39m]\u001b[38;5;241m.\u001b[39mfilename \u001b[38;5;28;01mif\u001b[39;00m relevant_files \u001b[38;5;28;01melse\u001b[39;00m metadata\u001b[38;5;241m.\u001b[39mfile_metadata_list[\u001b[38;5;241m0\u001b[39m]\u001b[38;5;241m.\u001b[39mfilename\n\u001b[0;32m---> 36\u001b[0m     shard \u001b[38;5;241m=\u001b[39m \u001b[43mcreate_shard_file\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpath\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmetadata\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mid\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mcpu\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43msingle_file\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     37\u001b[0m     shards \u001b[38;5;241m=\u001b[39m [shard]\n\u001b[1;32m     38\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n",
      "File \u001b[0;32m~/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py:79\u001b[0m, in \u001b[0;36mcreate_shard_file\u001b[0;34m(output_dir, repo_id, device, shard_filename, keys)\u001b[0m\n\u001b[1;32m     77\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mcreate_shard_file\u001b[39m(output_dir: Path, repo_id: \u001b[38;5;28mstr\u001b[39m, device: DeviceIdentifier, shard_filename: \u001b[38;5;28mstr\u001b[39m, keys: Optional[List[\u001b[38;5;28mstr\u001b[39m]] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m ShardFile:\n\u001b[1;32m     78\u001b[0m     output_path \u001b[38;5;241m=\u001b[39m output_dir \u001b[38;5;241m/\u001b[39m shard_filename\n\u001b[0;32m---> 79\u001b[0m     \u001b[43mdownload_file\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrepo_id\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mshard_filename\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moutput_path\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     81\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m keys \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m     82\u001b[0m         file_type \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msafetensors\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m shard_filename\u001b[38;5;241m.\u001b[39mendswith(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m.safetensors\u001b[39m\u001b[38;5;124m\"\u001b[39m) \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mbin\u001b[39m\u001b[38;5;124m\"\u001b[39m\n",
      "File \u001b[0;32m~/repos/april-oss/flow-merge/flow_merge/lib/tensor_loader.py:60\u001b[0m, in \u001b[0;36mdownload_file\u001b[0;34m(repo_id, filename, local_dir)\u001b[0m\n\u001b[1;32m     58\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m Path(file_path)  \u001b[38;5;66;03m# Convert returned file_path to Path\u001b[39;00m\n\u001b[1;32m     59\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m---> 60\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mFailed to download \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfilename\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m from \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mrepo_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00me\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mRuntimeError\u001b[0m: Failed to download model.safetensors from Qwen/Qwen1.5-0.5B: 416 Client Error: Requested Range Not Satisfiable for url: https://cdn-lfs-us-1.huggingface.co/repos/68/82/6882b504b120594058440b1fa4f2dba656dac125cc5e12dc9637f72229c9ea71/a88bcf41b3fa9a20031b6b598abc11f694e35e0b5684d6e14dbe7e894ebbb080?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1716562260&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxNjU2MjI2MH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzY4LzgyLzY4ODJiNTA0YjEyMDU5NDA1ODQ0MGIxZmE0ZjJkYmE2NTZkYWMxMjVjYzVlMTJkYzk2MzdmNzIyMjljOWVhNzEvYTg4YmNmNDFiM2ZhOWEyMDAzMWI2YjU5OGFiYzExZjY5NGUzNWUwYjU2ODRkNmUxNGRiZTdlODk0ZWJiYjA4MD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=NwBGl4p6PA7wYwoLJlt5ifg518J9G4-HfVWVOIOqW9jDhwlFo42MeckN7y0Nh1ShS~r4XsTOhqBEK1948wTJTKbnrAaxzZCEW3~aorw-oQI6xaJLlj-7N4SpLexpe6WZt6gt2F2ukCpomu8gq83k0BUkYvol9~VQ4FPmtfm608EPkOQW~YWtkwhR8NjKh9Rdj2sY5AIx4fMmbkx6dQVHcvLOPucdKak9d6RQIv5pz7oww1rVipl40ZPjH2ILwBMEjwz59kd9DidKEer2KBwlnDPfojqetBUaYiZ4d9rlQXYbR~n9fyn9CA3XSMuSZzrO8XgeN5rqQDhNlE7bmTV2GA__&Key-Pair-Id=KCD77M1F0VK2B"
     ]
    }
   ],
   "source": [
    "\n",
    "from pathlib import Path\n",
    "from flow_merge.lib.model import Model\n",
    "\n",
    "mo = Model.from_path(Path(path_or_id))\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "flow-merge",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
